language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
  - PINS="functoria mirage-skeleton.dev:https://github.com/yomimono/mirage-skeleton.git#charrua-0.3 mirage-types:https://github.com/mirage/mirage.git mirage:https://github.com/mirage/mirage.git mirage-logs:https://github.com/samoht/mirage-logs.git"
  matrix:
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02 PACKAGE=mirage
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02 PACKAGE=mirage-types
