language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - EXTRA_REMOTES="git://github.com/mirage/mirage-dev.git"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
 matrix:
   - PACKAGE=mirage DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=unix
   - PACKAGE=mirage DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=xen
   - PACKAGE=mirage DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=virtio
   - PACKAGE=mirage DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=ukvm
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 MODE=unix
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 MODE=xen
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 MODE=virtio
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 MODE=ukvm
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.03.0 MODE=unix
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.03.0 MODE=xen
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.03.0 MODE=virtio
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.03.0 MODE=ukvm
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=unix
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=xen
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=virtio
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.02.3 MODE=ukvm
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.03.0 MODE=unix
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.03.0 MODE=xen
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.03.0 MODE=virtio
   - PACKAGE=mirage-types DISTRO=debian-stable OCAML_VERSION=4.03.0 MODE=ukvm
#   - PACKAGE=mirage DISTRO=ubuntu-12.04 OCAML_VERSION=4.02.3
# ubuntu-12.04: too old a gcc
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0 MODE=unix
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0 MODE=xen
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0 MODE=virtio
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0 MODE=ukvm
#   - PACKAGE=mirage DISTRO=centos-6 OCAML_VERSION=4.02.3
# centos-6: too old a gcc
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 MODE=unix
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 MODE=xen
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 MODE=virtio
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 MODE=ukvm
   - PACKAGE=mirage DISTRO=fedora-24 OCAML_VERSION=4.02.3 MODE=unix
   - PACKAGE=mirage DISTRO=fedora-24 OCAML_VERSION=4.02.3 MODE=xen
   - PACKAGE=mirage DISTRO=fedora-24 OCAML_VERSION=4.02.3 MODE=virtio
   - PACKAGE=mirage DISTRO=fedora-24 OCAML_VERSION=4.02.3 MODE=ukvm
#   - PACKAGE=mirage DISTRO=alpine OCAML_VERSION=4.03.0
# alpine: openlibm needs refreshing to latest
