language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
  - UPDATE_GCC_BINUTILS=1
  - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
  matrix:
  - PACKAGE=mirage OCAML_VERSION=4.03
  - PACKAGE=mirage-types OCAML_VERSION=4.03
  - PACKAGE=mirage OCAML_VERSION=4.02
  - PACKAGE=mirage-types OCAML_VERSION=4.02
