language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
   - PINS="mirage:. mirage-types:. mirage-types-lwt:. mirage-runtime:."
   - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
   - PACKAGE=mirage
   - TESTS=false
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.07 EXTRA_ENV="MODE=unix" TESTS=true
   - DISTRO=alpine OCAML_VERSION=4.07 EXTRA_ENV="MODE=virtio"
   - DISTRO=alpine OCAML_VERSION=4.08 EXTRA_ENV="MODE=spt"
   - DISTRO=ubuntu OCAML_VERSION=4.08 EXTRA_ENV="MODE=xen"
   - DISTRO=alpine OCAML_VERSION=4.08 EXTRA_ENV="MODE=muen"
   - DISTRO=debian-stable OCAML_VERSION=4.08 EXTRA_ENV="MODE=hvt"
   - DISTRO=alpine OCAML_VERSION=4.07 EXTRA_ENV="MODE=qubes"
