language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
  - PACKAGE=functoria
  - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
  - PINS="mirage-skeleton.dev:https://github.com/mirage/mirage-skeleton.git"
  matrix:
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02
